services:
  - type: web
    name: voice-phishing-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --worker-class sync api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TF_ENABLE_ONEDNN_OPTS
        value: 0
      - key: FLASK_ENV
        value: production
